# Generated by Django 6.0.6 on 2026-07-07 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, null=True)),
                ('product_image', models.ImageField(null=True, upload_to='media/product')),
                ('Department', models.CharField(choices=[('Electronic', 'Electronic'), ('Cloth', 'Cloth'), ('Food', 'Food')], null=True)),
                ('price', models.PositiveIntegerField(null=True)),
                ('Description', models.TextField(max_length=200, null=True)),
            ],
        ),
    ]
