# Generated by Django 6.0.5 on 2026-07-08 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='Date',
            field=models.DateField(null=True),
        ),
    ]
