# Generated by Django 5.2.14 on 2026-07-08 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_productmodel_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='forkeymodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cateogry_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='productmodel',
            name='quantity',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.forkeymodel'),
        ),
    ]
