# Generated by Django 5.2.14 on 2026-07-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_forkeymodel_productmodel_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='Department',
            field=models.CharField(choices=[('Electronic', 'Electronic'), ('Cloth', 'Cloth'), ('Food', 'Food')], max_length=100, null=True),
        ),
    ]
