# Generated by Django 5.2.14 on 2026-07-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_alter_productmodel_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
